@extends('layouts.admin')
@section('content')

<style>
    .gps-delete {
        border-radius: 28px;
        overflow: hidden;
        background:
            radial-gradient(circle at 14% 18%, rgba(255, 173, 91, 0.18), transparent 18%),
            radial-gradient(circle at 84% 12%, rgba(255, 85, 85, 0.14), transparent 22%),
            linear-gradient(135deg, #101c2f 0%, #18253a 56%, #0a111b 100%);
        border: 1px solid rgba(255,255,255,0.08);
        box-shadow: 0 28px 56px rgba(10, 17, 27, 0.24);
        position: relative;
        color: rgba(255,255,255,0.9);
    }

    .gps-delete::before {
        content: "";
        position: absolute;
        inset: 0;
        background:
            linear-gradient(rgba(95, 243, 255, 0.05) 1px, transparent 1px),
            linear-gradient(90deg, rgba(95, 243, 255, 0.05) 1px, transparent 1px);
        background-size: 38px 38px;
        pointer-events: none;
    }

    .gps-delete__content {
        position: relative;
        z-index: 1;
        padding: 34px;
    }

    .gps-delete__eyebrow {
        color: #ffb347;
        text-transform: uppercase;
        letter-spacing: 0.34rem;
        font-size: 0.72rem;
        margin-bottom: 12px;
    }

    .gps-delete__title {
        font-family: Bahnschrift, "Trebuchet MS", sans-serif;
        font-size: 2rem;
        margin-bottom: 10px;
    }

    .gps-delete__text {
        color: rgba(255,255,255,0.72);
        max-width: 640px;
    }

    .gps-delete__panel {
        border-radius: 22px;
        background: rgba(255,255,255,0.06);
        border: 1px solid rgba(255,255,255,0.08);
        padding: 24px;
        margin: 28px 0;
        backdrop-filter: blur(6px);
    }

    .gps-delete__grid {
        display: grid;
        grid-template-columns: repeat(2, minmax(0, 1fr));
        gap: 18px;
    }

    .gps-delete__label {
        color: rgba(255,255,255,0.58);
        text-transform: uppercase;
        font-size: 0.74rem;
        letter-spacing: 0.18rem;
        margin-bottom: 8px;
    }

    .gps-delete__value {
        font-family: Bahnschrift, "Trebuchet MS", sans-serif;
        font-size: 1.08rem;
    }

    .gps-delete__actions {
        display: flex;
        flex-wrap: wrap;
        gap: 12px;
    }

    @media (max-width: 767px) {
        .gps-delete__content {
            padding: 24px;
        }

        .gps-delete__grid {
            grid-template-columns: 1fr;
        }

        .gps-delete__title {
            font-size: 1.6rem;
        }
    }
</style>

<div class="gps-delete">
    <div class="gps-delete__content">
        <div class="gps-delete__eyebrow">Delete Confirmation</div>
        <div class="gps-delete__title">Remove GPS Smart Card from Registry</div>
        <p class="gps-delete__text">
            Ye action selected card ko listing se remove kar dega. Agar same batch ke aur cards hain to un par koi effect nahi padega, sirf yahi record soft-delete hoga.
        </p>

        <div class="gps-delete__panel">
            <div class="gps-delete__grid">
                <div>
                    <div class="gps-delete__label">Card Number</div>
                    <div class="gps-delete__value">{{ $gpsCard->formatted_card_number }}</div>
                </div>
                <div>
                    <div class="gps-delete__label">Batch Code</div>
                    <div class="gps-delete__value">{{ $gpsCard->batch_code }}</div>
                </div>
                <div>
                    <div class="gps-delete__label">Product Model</div>
                    <div class="gps-delete__value">{{ $gpsCard->productModel->product_model ?? 'N/A' }}</div>
                </div>
                <div>
                    <div class="gps-delete__label">Batch Size</div>
                    <div class="gps-delete__value">{{ $batchCount }} Cards</div>
                </div>
                <div>
                    <div class="gps-delete__label">Validity</div>
                    <div class="gps-delete__value">{{ $gpsCard->formatted_valid_from }} - {{ $gpsCard->formatted_valid_to }}</div>
                </div>
                <div>
                    <div class="gps-delete__label">Generated By</div>
                    <div class="gps-delete__value">{{ $gpsCard->createdBy->name ?? 'System User' }}</div>
                </div>
            </div>
        </div>

        <div class="gps-delete__actions">
            <a href="{{ route('admin.gps-cards.show', $gpsCard->id) }}" class="btn btn-light">
                <i class="fas fa-arrow-left mr-1"></i> Back to Card
            </a>
            <a href="{{ route('admin.gps-cards.index') }}" class="btn btn-outline-light">
                Cancel
            </a>
            <form action="{{ route('admin.gps-cards.destroy', $gpsCard->id) }}" method="POST" onsubmit="return confirm('Delete this GPS smart card?');">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger px-4">
                    <i class="fas fa-trash mr-1"></i> Delete Now
                </button>
            </form>
        </div>
    </div>
</div>

@endsection
